
name: Python3 CI

on: 
  push:
    branches:
      - "bootcamp**"
      

jobs:

  test:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        python main.py
        python test.py
